### ISSUE TITLE
兼容非 http(s) 开头长链接

### ISSUE THREAD

**Issue by GaoangLiu** [Closty/duanwangzhi#2]
很方便，效果很棒。 

代码有一个小问题，当输入的长链接不是以  http(s)  开头的时候，返回的结果为 t.cn/$url 。
即如果输入 google.com 返回的短链对应  https://t.cn/google.com，而不是期望的 https://www.google.com 

能否稍做修改，在代码里为非 http 开头的链接自动补齐前缀?

**Comment by Closty** [comment]
很好的问题，不过本文档是给开发人员看的，因此选择80端口还是443端口由他们选择吧

**Comment by Closty** [comment]
> 很方便，效果很棒。
> 
> 代码有一个小问题，当输入的长链接不是以 http(s) 开头的时候，返回的结果为 t.cn/$url 。
> 即如果输入 google.com 返回的短链对应 [https://t.cn/google.com，而不是期望的](https://t.cn/google.com%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF%E6%9C%9F%E6%9C%9B%E7%9A%84) https://www.google.com
> 
> 能否稍做修改，在代码里为非 http 开头的链接自动补齐前缀?

很好的问题，不过本文档是给开发人员看的，因此选择80端口还是443端口由他们选择吧

**Comment by GaoangLiu** [comment]
> > 很方便，效果很棒。
> > 代码有一个小问题，当输入的长链接不是以 http(s) 开头的时候，返回的结果为 t.cn/$url 。
> > 即如果输入 google.com 返回的短链对应 [https://t.cn/google.com，而不是期望的](https://t.cn/google.com%EF%BC%8C%E8%80%8C%E4%B8%8D%E6%98%AF%E6%9C%9F%E6%9C%9B%E7%9A%84) https://www.google.com
> > 能否稍做修改，在代码里为非 http 开头的链接自动补齐前缀?
> 
> 很好的问题，不过本文档是给开发人员看的，因此选择80端口还是443端口由他们选择吧

也是，大家需求不一样。
