### ISSUE TITLE
请教一下这个api该怎么写

### ISSUE THREAD

**Issue by PedroZhang** [Closty/duanwangzhi#4]
https://api.uomg.com/doc-long2dwz.html
这个api我试了是可以生成tcn的，不太会写，一直返回失败。所以请教一下大佬怎么接入。方便的话麻烦您教一下。谢谢

**Comment by Closty** [comment]
你找的这个网址我看了，不管用不用这个项目，其网址本身的api接口自带问题，如访问
https://api.uomg.com/api/long2fh?url=https://www.clost.net

并不会返回短网址，而是返回{"code":1,"msg":"existence","ae_url":"http://check.uomg.com/","longurl":"http://check.uomg.com/"}

**Comment by PedroZhang** [comment]
应该是这样
https://api.uomg.com/api/long2dwz?dwzapi=tcn&url=https://www.clost.net
返回{"code":1,"ae_url":"http:\/\/t.cn\/A6wT0J1d"}

**Comment by Closty** [comment]
好，明天晚上十点前上传。你这个应该是改了接口没改匹配html.match那个，之前是直接返回http://t.cn而你的是带正向规则的http:\/\/t.cn多了几个符号，把它改好就行啦。我写作业啦

**Comment by PedroZhang** [comment]
谢谢大佬
